payload:
  - DOMAIN-SUFFIX,apifox.it.com
  - DOMAIN-SUFFIX,cdn.openroute.dev
  - DOMAIN-SUFFIX,feishu.it.com
  - DOMAIN-SUFFIX,system.toshinkyo.or.jp
  - DOMAIN-SUFFIX,checkmarx.zone
  - DOMAIN-SUFFIX,litellm.cloud
